server:
  port: 8888

api-key: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978

resources:
  windows-resource: file:C:/FbStrandingUI/Resource/
  linux-resource: file:/FbStrandingUI/Resource/

competitions:
  urls:
    getLeagues: https://apiv2.apifootball.com/?action=get_leagues&country_id={countryId}&APIkey=${api-key}
    getCountries: https://apiv2.apifootball.com/?action=get_countries&APIkey=${api-key}
    getTeams: https://apiv2.apifootball.com/?action=get_teams&league_id={leagueId}&APIkey=${api-key}
    getStranding: https://apiv2.apifootball.com/?action=get_standings&league_id={leagueId}&APIkey=${api-key}